# Generated by Django 5.0.4 on 2024-05-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nameApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinterest',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='petinterest',
            name='moreInfo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='petinterest',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
